[MM-987]: Added setup and webhook command to system admin help text
mattermost/mattermost-plugin-jira pull request #1125
Opened 2024-09-26 07:14 UTC by Kshitij-Katiyar

### Summary
Added setup and webhook command to system admin help text
### Issue link
 fixes https://github.com/mattermost/mattermost-plugin-jira/issues/987
### Screenshots
#### Existing
![Screenshot from 2024-09-20 17-03-03](https://github.com/user-attachments/assets/174ee24c-c033-40d4-9576-ef893909e3f4)
#### Updated
![Screenshot from 2024-09-20 17-02-06](https://github.com/user-attachments/assets/ae7edec2-7b13-4cda-a77c-598876058e15)

2024-10-22 20:07 UTC, wiggin77 approved these changes

2024-10-24 10:24 UTC, raghavaggarwal2308 requested changes

2024-10-24 10:24 UTC, raghavaggarwal2308 commented on server/command.go
> -	"* `/jira webhook [--instance=<jiraURL>]` -  Show the Mattermost webhook to receive JQL queries\n" +
Why have we removed this?

2024-10-24 11:16 UTC, raghavaggarwal2308 commented on server/command.go
> -	"* `/jira webhook [--instance=<jiraURL>]` -  Show the Mattermost webhook to receive JQL queries\n" +
Discussed, this functionality has been removed from the plugin

2024-10-24 11:16 UTC, raghavaggarwal2308 approved these changes

2024-10-24 11:16 UTC, merged