[MM-1121]: Fix epic selector not displaying options if field is renamed in Jira
mattermost/mattermost-plugin-jira pull request #1134
Opened 2024-11-05 08:21 UTC by Kshitij-Katiyar

#### Summary
- The `Create Issue` modal had a bug: if the `Epic` field in a Jira project was renamed to anything other than `Epic`, the dropdown for selecting Jira epics displayed no options.
- The existing logic iterates over each field in the Jira project, filtering for fields named `Epic`, and then checks if the filtered field matches the Epic field schema before fetching all epics from the project.
- The bug occurred because the code depended solely on finding a field named `Epic`. This PR removes the name-based check and instead relies exclusively on the field schema to identify the Epic field.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1121

2024-12-22 15:32 UTC, raghavaggarwal2308 requested changes
Please add proper QA testing steps. As the QA will not know about renaming the fields on Jira side.

2024-12-22 15:32 UTC, raghavaggarwal2308 commented on webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
> +            }
This will always be false. I think we can remove this

2024-12-22 15:32 UTC, raghavaggarwal2308 commented on webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
> +            }
Never true, can be removed

2024-12-22 15:32 UTC, raghavaggarwal2308 commented on webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
> +            }
Can create a util for this

2025-01-16 14:28 UTC, Kshitij-Katiyar commented on webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
> +            }
used only once

2025-01-16 14:28 UTC, Kshitij-Katiyar commented on webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
> +            }
the above similar code has a different functionality

2025-01-16 14:34 UTC, Kshitij-Katiyar commented
> Please add proper QA testing steps. As the QA will not know about renaming the fields on Jira side.

No need to rename the field, added the link

2025-02-03 16:37 UTC, wiggin77 approved these changes
LHTM :+1:

2025-02-04 07:58 UTC, Kshitij-Katiyar commented
@AayushChaudhary0001 Please test this PR

2025-03-20 11:07 UTC, arush-vashishtha commented
I have tested the epic selector for the renamed epic fields in the Jira create issue modal and it is working fine. LGTM.
![image](https://github.com/user-attachments/assets/6ed9b781-bc0f-41fb-8d3d-7681e2a62d50)
![image](https://github.com/user-attachments/assets/46f633fc-306e-4334-9745-c2e2926a95f6)

2025-03-20 12:23 UTC, merged