[GH-622] Bump version to v3.0.0
mattermost/mattermost-plugin-jira pull request #669
Opened 2020-09-25 15:42 UTC by jfrerich

#### Summary
Bump version to v3.0.0

#### Ticket Link
#622

2020-09-25 17:12 UTC, hanzei commented
/update-branch

2020-09-25 17:12 UTC, levb approved these changes

2020-09-25 17:12 UTC, hanzei requested changes

2020-09-25 17:12 UTC, hanzei commented on plugin.json
>    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v2.4.0",
This need up get updated

2020-09-25 17:17 UTC, hanzei approved these changes
:rocket:

2020-09-28 15:07 UTC, aaronrothschild approved these changes
LGTM

2020-10-01 22:45 UTC, DHaussermann commented
/update-branch

2020-10-02 15:53 UTC, DHaussermann commented
/update-branch

2020-10-02 15:53 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2020-10-02 15:54 UTC, DHaussermann commented
At @hanzei  can you please help? 
The only PR added to master should be https://github.com/mattermost/mattermost-plugin-jira/pull/681 
I can't pull it up into this branch.

2020-10-02 15:57 UTC, hanzei commented
@DHaussermann Conflict resolved

2020-10-02 18:54 UTC, DHaussermann approved these changes
- Ran through end 2 end test for all precasting Jira 2.4 functionality
- Ran through end 2 end test for new Jira V3 functionality
- Tested Jira migration of Cloud  and server instanced - No issues found
- Tested Jira denigrate with both reinstall  Jira 2.4 path and the re-enable Jira 3 path
- Tested last change for min server version
- Version correctly shown as `3.0.0`

2020-10-02 18:56 UTC, DHaussermann commented
@jfrerich Let me know once we have a version in the repo. 
We can then have it applied to community and create a marketplace PR 🎉

2020-10-02 19:15 UTC, merged