Add return empty Instances in store.LoadInstances if not found
mattermost/mattermost-plugin-jira pull request #671
Opened 2020-09-26 22:00 UTC by vladimirdotk

#### Summary
- Add return empty Instances in store.LoadInstances if not found

#### Ticket Link
Fixes #642

2020-10-08 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-08 11:50 UTC, jasonblais commented
@mickmister and @jfrerich quick reminder to help with reviews :)

2020-10-08 16:06 UTC, mickmister approved these changes
Thanks @vladimirdotk! Great work :+1:

2020-10-08 23:08 UTC, jfrerich approved these changes
Thanks for the PR, @vladimirdotk!

2020-10-19 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-19 11:14 UTC, jasonblais commented
@DHaussermann kind reminder to help with reviews :)

2020-10-19 14:17 UTC, DHaussermann commented
/update-branch

2020-10-19 14:48 UTC, mickmister requested changes
Thanks @vladimirdotk! I have one request on initializing the `Instances` struct

2020-10-19 14:48 UTC, mickmister commented on server/kv.go
> +		return &Instances{}, nil
There is a panic happening due to this `Instances` not being properly initialized. Can we change this line to the following?

```suggestion
		return NewInstances(), nil
```

2020-10-19 16:07 UTC, mickmister approved these changes
Great work @vladimirdotk! Thanks for your contribution!!

2020-10-19 17:59 UTC, DHaussermann approved these changes
Tested and passed
- Install issue is now resolved! 
- When the list command is run and there is nothing to list, I now see a much friendlier `(none installed)` as opposed to the previous `Failed to load known Jira instances: instances/v3: not found`
- Confirmed in system logs that the error no longer occurs when there are no instances and the command is run to retrieve them
- Regression tested installing and connecting to an instance
LGTM!

Thanks @vladimirdotk for this fix. Much appreciated!

2020-10-20 15:56 UTC, merged