[GH-149] Send ephemeral message after /jira connect flow succeeds
mattermost/mattermost-plugin-jira pull request #711
Opened 2020-10-27 01:47 UTC by promulo

#### Summary
This PR sends an ephemeral message to the user after the `/jira connect` flow is completed. Please check this comment regarding this issue, as this PR does not address all the requirements.

#### Ticket Link
GH-149

2020-10-27 01:47 UTC, mattermod commented
Hello @promulo,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-02 15:35 UTC, aaronrothschild requested changes
Thanks for the contribution @promulo !

2020-11-02 15:41 UTC, jasonblais commented
@aaronrothschild did you mean to accept or request changes?

2020-11-02 15:41 UTC, jasonblais commented
cc @levb @jfrerich for dev review

2020-11-02 16:35 UTC, aaronrothschild commented
> @aaronrothschild did you mean to accept or request changes?

@promulo Sorry, I mean to request the small wording change for the user. Otherwise, all good.

2020-11-02 17:14 UTC, promulo commented
Sorry @aaronrothschild but what would be the wording change here? Do you mean the inclusion of the user e-mail in the message?

2020-11-02 17:39 UTC, aaronrothschild commented on webapp/src/actions/index.ts
> +            store.dispatch(sendEphemeralPost('You have successfully connected your Jira account.'));
```suggestion
            store.dispatch(sendEphemeralPost('You have successfully connected your Jira account. Type in /jira to get started. '));
```

2020-11-02 17:40 UTC, aaronrothschild commented on webapp/src/actions/index.ts
> +            store.dispatch(sendEphemeralPost('You have successfully connected your Jira account.'));
Sorry - Github gave me some issues today.... the comment didn't post.  Added it now. small change to text of what bot says.

2020-11-04 21:42 UTC, aaronrothschild approved these changes
Awesome, thanks!

2020-11-07 20:55 UTC, levb approved these changes

2020-11-10 20:53 UTC, jfrerich approved these changes

2020-11-18 16:20 UTC, DHaussermann commented
/update-branch

2020-11-19 14:33 UTC, DHaussermann commented
Thanks @promulo  for this PR. Sorry for the delay in testing. 

This is certainly an improvement in the UX. One Minor point is that it would feel more consistent if the ephemeral post was made by the Jira bot rather than a system post. I don't know if this is a minor change or something we should make a separate enhancement issue for?   

![Screen Shot 2020-11-19 at 9 29 44 AM](https://user-images.githubusercontent.com/35588783/99679553-0ed94a80-2a4a-11eb-9603-ee65afcfb3e2.png)

@aaronrothschild Should I create a separate issue for this?

2020-11-19 18:35 UTC, promulo commented
Hi @DHaussermann, just as FYI there is already an issue for that: https://github.com/mattermost/mattermost-plugin-jira/issues/560 :)

2020-11-19 18:43 UTC, DHaussermann commented
My mistake thanks @promulo for pointing that out 😂

2020-11-19 18:45 UTC, DHaussermann approved these changes
Tested and passed
- Ephemeral post confirms connection as expected
- Tested when connecting to both Jira Cloud and Server instaces
- https://github.com/mattermost/mattermost-plugin-jira/issues/560 will address posts not being made by the Jira bot.

LGTM!

2020-11-20 02:37 UTC, merged

2020-11-20 02:37 UTC, hanzei commented
Thanks @promulo :+1: