[Fix:#722] : Check errors for LoadInstances() call
mattermost/mattermost-plugin-jira pull request #730
Opened 2020-12-17 05:43 UTC by haardikdharma10

#### Summary

This PR aims to solve #722 

#### Ticket Link

#722

2020-12-17 05:43 UTC, mattermod commented
Hello @haardikdharma10,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-18 00:02 UTC, jfrerich approved these changes
Thanks, @haardikdharma10.  This was actually a bug on my part.

2020-12-18 05:27 UTC, haardikdharma10 commented
> Thanks, @haardikdharma10. This was actually a bug on my part.

No worries:)

2020-12-21 16:56 UTC, mickmister requested changes
Thanks for tackling this task @haardikdharma10 :+1: Looking through the codebase, it looks like there is some error checks missing in `instances.go`. Do you mind checking out that file to find the other places to check for this error?

2020-12-22 21:04 UTC, haardikdharma10 commented
@mickmister, sure thing.

2021-01-02 19:15 UTC, haardikdharma10 commented
Hi @mickmister, I face some difficulties to check for errors in the instances.go file. Do you mind creating a separate ticket for that and maybe we can merge this PR as it solves #722 ?

2021-01-03 03:12 UTC, mickmister commented
> Hi @mickmister, I face some difficulties to check for errors in the instances.go file

@haardikdharma10 Do you mind explaining the difficulties you've encountered?

> Do you mind creating a separate ticket for that and maybe we can merge this PR as it solves #722 ?

I would think that the cases in `instances.go` are part of the same task. Is there a reason this is not the case? We can change the scope of the task if necessary.

2021-01-14 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-14 14:42 UTC, jfrerich commented
Hi @haardikdharma10, have you had a chance to review the response from @mickmister?

2021-01-14 18:57 UTC, haardikdharma10 commented
Hi @jfrerich, sorry for the delay on this. Just a quick question, what should be the `http.Request` error here, when the instances fail to load? Will it be `http.StatusBadRequest` or something else?

2021-01-15 04:19 UTC, mickmister commented
> what should be the `http.Request` error here, when the instances fail to load? Will it be `http.StatusBadRequest` or something else?

@haardikdharma10 I think `http.StatusInternalServerError` should be used because the issue is purely on the server, such as a database error. `http.StatusBadRequest` should be used when the client's request has a missing value for example.

2021-01-15 04:38 UTC, haardikdharma10 commented
Got it! Thank you @mickmister, and sorry if I ask a lot of questions :D

2021-01-15 06:16 UTC, mickmister requested changes
Thanks @haardikdharma10! I have one last request here to include some context on the errors. Otherwise looks great :+1:

2021-01-15 06:16 UTC, mickmister commented on server/instances.go
> +		return respondErr(w, http.StatusInternalServerError, err)
```suggestion
		return respondErr(w, http.StatusInternalServerError, errors.Wrap(err, "failed to load instances"))
```

2021-01-15 06:16 UTC, mickmister commented on server/instances.go
> +		return respondErr(w, http.StatusInternalServerError, err)
```suggestion
		return respondErr(w, http.StatusInternalServerError, errors.Wrap(err, "failed to load instances"))
```

2021-01-15 06:16 UTC, mickmister commented on server/instances.go
> +		return "", err
```suggestion
		return "", errors.Wrap(err, "failed to load instances")
```

2021-01-15 06:37 UTC, haardikdharma10 commented
Applied your suggestions. Thank you for your time @mickmister :)

2021-01-15 21:23 UTC, mickmister approved these changes
LGTM thanks @haardikdharma10!!

2021-01-15 21:23 UTC, merged