Fix #615: Rename channel_settings files to channel_subscriptions
mattermost/mattermost-plugin-jira pull request #731
Opened 2021-01-08 13:56 UTC by haardikdharma10

#### Summary

This PR aims to solve #615 

#### Ticket Link

Issue: #615

2021-01-08 13:56 UTC, mattermod commented
Hello @haardikdharma10,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-13 17:26 UTC, jfrerich approved these changes
Awesome!  Thank you, @haardikdharma10!

2021-01-13 18:23 UTC, mickmister requested changes
Great work @haardikdharma10! Thanks for tackling this task

I have a request to rename some of the plural `ChannelSubscriptions` to `ChannelSubscription`, for cases where we are only working with one subscription. Other than this, the PR looks perfect :+1:

2021-01-13 18:23 UTC, mickmister commented on webapp/src/components/modals/channel_subscriptions/channel_subscriptions_filter.tsx
> +export default class ChannelSubscriptionsFilter extends React.PureComponent<Props, State> {
```suggestion
export default class ChannelSubscriptionFilter extends React.PureComponent<Props, State> {
```

2021-01-13 18:23 UTC, mickmister commented on webapp/src/components/modals/channel_subscriptions/channel_subscriptions_filter.tsx
> +type EmptyChannelSubscriptionsFilterProps = {
```suggestion
type EmptyChannelSubscriptionFilterProps = {
```

2021-01-13 18:23 UTC, mickmister commented on webapp/src/components/modals/channel_subscriptions/channel_subscriptions_filter.tsx
> +export function EmptyChannelSubscriptionsFilter(props: EmptyChannelSubscriptionsFilterProps): JSX.Element {
```suggestion
export function EmptyChannelSubscriptionFilter(props: EmptyChannelSubscriptionFilterProps): JSX.Element {
```

2021-01-13 18:23 UTC, mickmister commented on webapp/src/components/modals/channel_subscriptions/channel_subscriptions_filters.tsx
> +export default class ChannelSubscriptionsFilters extends React.PureComponent<Props, State> {
```suggestion
export default class ChannelSubscriptionFilters extends React.PureComponent<Props, State> {
```

2021-01-13 18:23 UTC, mickmister commented on webapp/src/components/modals/channel_subscriptions/edit_channel_subscriptions.tsx
> +export default class EditChannelSubscriptions extends PureComponent<Props, State> {
```suggestion
export default class EditChannelSubscription extends PureComponent<Props, State> {
```

2021-01-13 18:35 UTC, haardikdharma10 commented
@mickmister, yes, that makes sense. Applied your suggestions. Thanks for the review:)

2021-01-13 19:33 UTC, haardikdharma10 commented
Hi @mickmister, here: 

```
import {ChannelSubscription, ChannelSubscriptionFilters, ReactSelectOption, FilterValue, IssueMetadata} from 'types/model';

import ChannelSubscriptionsFilters from './channel_subscriptions_filters';
```

When I try to change `ChannelSubscriptionsFilters` to  `ChannelSubscriptionFilters` in the second import statement (as suggested by you) it gives me an error as follows:

<img width="694" alt="Screenshot 2021-01-14 at 12 57 43 AM" src="https://user-images.githubusercontent.com/53044263/104500155-0c3b4180-5604-11eb-9f1b-d9dd9c635d1c.png">

as it is duplicated from the first import statement, which is leading to coverage errors if not changed. What should be done in this case?

2021-01-13 20:25 UTC, mickmister commented
@haardikdharma10 It looks like there's a conflict between the name of the type in `types/model.ts` called `ChannelSubscriptionFilters`, and the React component's name. I think this solution should work:

```ts
import {ChannelSubscriptionFilters as ChannelSubscriptionFiltersModel} from 'types/model';

import ChannelSubscriptionsFilters from './channel_subscriptions_filters';
```

2021-01-13 20:31 UTC, mickmister commented
@haardikdharma10 Can we also rename the files to singular like
`channel_subscriptions_filter -> channel_subscription_filter`

2021-01-14 07:31 UTC, haardikdharma10 commented
@mickmister, all test cases pass and this PR is ready for re-review 😅

2021-01-15 06:22 UTC, mickmister approved these changes
Awesome work @haardikdharma10! This is a great improvement to the codebase :+1:

2021-01-19 05:54 UTC, haardikdharma10 commented
ping @DHaussermann, can you please review this PR and let us know if this is good to go!? Thanks :)

2021-01-27 15:03 UTC, DHaussermann commented
/update-branch

2021-01-27 19:52 UTC, DHaussermann approved these changes
Tested and passed
Regression tested subscriptions functionality for this change
- Performed Create/Update/Delete testing of subscriptions
- Ensured channel notices still work when subscriptions are edited 
- Subscription list modal and create/edit modal behave normally 
- Confirmed subscriptions are still functional and Projects, Event, additional filters etc... get updated properly and subscriptions get delivered accordingly
- Subscribe list still works as expected   

LGTM!

No issues found. 
No new release tests needed to cover this. 

@haardikdharma10 huge thanks for this enhancement. Much appreciated! My apologies for the delay in testing this change.

2021-01-28 13:18 UTC, merged