Clarify Enterprise required for multiple instances
mattermost/mattermost-plugin-jira pull request #765
Opened 2021-04-16 22:04 UTC by bbodenmiller

Update docs to match main readme

2021-04-21 20:18 UTC, mickmister requested changes

2021-04-21 20:18 UTC, mickmister commented on docs/README.md
> +**Support for multiple Jira instances is supported from Jira 3.0 for Mattermost Enterprise Editions and configured using [Administrator Slash Commands](https://mattermost.gitbook.io/plugin-jira/admin
An E20 license is required to use the feature, i.e. an instance with an E10 enterprise license won't work. Can we keep the part about E20 in to be clear?

2021-04-26 15:58 UTC, mickmister approved these changes
Great work, thanks @bbodenmiller!

2021-05-07 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-05-12 14:13 UTC, justinegeffen commented on docs/README.md
> +**Support for multiple Jira instances is supported from Jira 3.0 for Mattermost Enterprise E20 and configured using [Administrator Slash Commands](https://mattermost.gitbook.io/plugin-jira/administra
```suggestion
**Support for multiple Jira instances is supported from Jira 3.0 for Mattermost Enterprise Edition E20 and configured using [Administrator Slash Commands](https://mattermost.gitbook.io/plugin-jira/administrator-guide/administrator-slash-commands).**
```

2021-05-12 14:13 UTC, justinegeffen commented on readme.md
> +From v3.0 of this plugin, support for multiple Jira instances is offered for Mattermost Enterprise E20.
```suggestion
From v3.0 of this plugin, support for multiple Jira instances is offered for Mattermost Enterprise Edition E20.
```

2021-05-12 14:14 UTC, justinegeffen approved these changes

2021-05-12 15:14 UTC, merged