Fixed plugin failure on Issue with no priority.
mattermost/mattermost-plugin-jira pull request #821
Opened 2021-11-16 19:06 UTC by DummyThatMatters

#### Summary
Fixes the situation when plugin process the issue with Priority field set to `nil`, which can potentially lead to situation when nill pointer dereference error occurs.

#### Ticket Link
Seem to fix https://github.com/mattermost/mattermost-plugin-jira/issues/820

2021-11-16 19:06 UTC, mattermod commented
Hello @DummyThatMatters,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-11-18 20:50 UTC, mickmister commented
Hi @DummyThatMatters, thanks for catching this and providing the fix :tada: 

Just so I can understand the issue better, do you know if this is occurring in one of these two cases:

- the issue scheme does not contain the `priority` field
- the issue scheme does have a `priority`, but the priority is not assigned for a given issue somehow

As far as the fix you've provided, I have one request to provide the same fix to other fields potentially having this issue in the same function. Thanks for this great contribution @DummyThatMatters!

2021-11-18 20:50 UTC, mickmister requested changes

2021-11-22 12:16 UTC, DummyThatMatters commented on server/issue.go
> +		}
> Hi @DummyThatMatters, thanks for catching this and providing the fix 🎉
> 
> Just so I can understand the issue better, do you know if this is occurring in one of these two cases:
> 
>     * the issue scheme does not contain the `priority` field
> 
>     * the issue scheme does have a `priority`, but the priority is not assigned for a given issue somehow
> 
> 
> As far as the fix you've provided, I have one request to provide the same fix to other fields potentially having this issue in the same function. Thanks for this great contribution @DummyThatMatters!

Frankly, I don't really know. Does this thing matter? We debugged this a long time ago and I have implemented my patch on our prod server, so it no longer fail and I don't know which exact tickets caused the issue. 
I can try to find out if this info is essential in order to investigate the bug and fix potential problems. And we do not have any problems with other fields for some reason.

2021-12-03 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2022-01-13 21:11 UTC, mickmister commented on server/issue.go
> +		}
@DummyThatMatters Fair enough, I'll approve at its current state. Note that you'll need to sign our CLA before getting this merged, as explained here https://github.com/mattermost/mattermost-plugin-jira/pull/821#issuecomment-970582277

Thanks again for this fix 😄

2022-01-13 21:11 UTC, mickmister approved these changes

2022-04-27 10:44 UTC, dipak-demansol commented
@DummyThatMatters priority is a mandatory field at the time of creating jira issue using the plugin so how you reported the issue with No priority?

2022-04-27 12:04 UTC, dipak-demansol commented
> @DummyThatMatters priority is a mandatory field at the time of creating jira issue using the plugin so how you reported the issue with No priority?

@mickmister can you give me some info to regenerate the issue?

2022-04-27 13:38 UTC, DummyThatMatters commented
> @DummyThatMatters priority is a mandatory field at the time of creating jira issue using the plugin so how you reported the issue with No priority?

@dipak-demansol hello! You can track issues that have not been created via plugin. then you'll have some problems with nil priority issues.

2022-04-27 20:32 UTC, mickmister commented
@dipak-demansol I think you'll need to have an issue schema that has a priority field, but no default value set for the field. Not entirely sure how that works though

2022-05-06 16:11 UTC, dipak-demansol commented
@DHaussermann We're trying to find a way to null out priority from web request.

2022-12-11 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-21 09:44 UTC, hanzei commented
/update-branch

2023-02-21 09:45 UTC, hanzei approved these changes

2023-02-21 09:45 UTC, hanzei commented
@DHaussermann Can we merge this straight forward fix would QA review?

2023-02-23 18:39 UTC, hanzei commented
@DummyThatMatters Would you be open on signing the CLA?

2023-02-27 22:46 UTC, DHaussermann commented
@hanzei If this is low risk - we should merge it without testing to resolve the problem. 

0/5 There may have simple ways to build the data needed for this in the past. But i believe this filed is automatically set even when removed from all configuration and not visible in the UI. (Jira seems to assign values which it uses to hold the order of tings in lists.)

In any case, I can find no simple way to create the data needed short of manipulating a DB. I suggest we merge this and rely on release testing to catch any regression.

2023-02-28 03:04 UTC, DHaussermann approved these changes
Please disregard previous comment. I had the filed and scenario confused with something else. 

Tested and passed.
Steps:
- Picked a project  
- Created a custom scheme for issues of type Bug within the ptoject
- Removed priority field from the scheme
- Confirmed the Jira webapp  could create the issue
- Confirmed the Jira plugin can create the same issue form within Mattermost

This issue is resolved. No regressions found

LGTM!

Thanks for the soulution @DummyThatMatters 🎉

2023-02-28 09:51 UTC, merged