Release 3.2.1
mattermost/mattermost-plugin-jira pull request #877
Opened 2022-10-01 12:57 UTC by mickmister

#### Summary

- https://github.com/mattermost/mattermost-plugin-jira/pull/868

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-jira/issues/876

2022-10-04 00:02 UTC, hanzei commented on Makefile
> +	git config --global url."ssh://git@".insteadOf git://
Do we need that or can we wait for the orb release?

2022-10-08 09:35 UTC, hanzei commented on Makefile
> +	git config --global url."ssh://git@".insteadOf git://
Let's remove this

2022-10-08 09:35 UTC, hanzei requested changes
See comment

2022-10-13 15:25 UTC, hanzei approved these changes

2022-10-31 12:07 UTC, mickmister commented
Superseded by https://github.com/mattermost/mattermost-plugin-jira/pull/884

2022-10-31 12:07 UTC, closed without merging