feat : dependabot workflow automation for updating dependency
mattermost/mattermost-plugin-jira pull request #882
Opened 2022-10-26 18:37 UTC by Rajpratik71

#### Summary

Dependabot workflow automation for updating dependency

#### Ticket Link

2022-10-26 18:37 UTC, mattermod commented
Hello @Rajpratik71,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-28 22:40 UTC, hanzei requested changes
I'm not sure if this small project really needs auto updates. Security updates are already provided via Dependabot.

What values do auto updates for dependencies provide?

2022-10-29 05:04 UTC, Rajpratik71 commented
Manual control of dependency is fine but with a growing no. of distributed upstream dependencies, it becomes hard to manage. So, for that automation should be there to update dependencies. Further, CI Pipeline is there to test those changes.


Further, this will not update the dependencies automatically, instead, a PR will be opened with changes that can be reviewed and tested with CI.

2022-11-01 08:04 UTC, hanzei commented
> Further, CI Pipeline is there to test those changes.

That is the part at worries me. CI does test something, but manually testing is still required. And doing that on every version bump PR seems like a lot of work.

2022-11-12 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-12 05:59 UTC, closed without merging